### ISSUE TITLE
Unable create pool on devnet

### ISSUE THREAD

**Issue by linxux** [raydium-io/raydium-sdk-V1-demo#13]
1. Change the `PROGRAMIDS` in `config.ts`
```diff
- export const PROGRAMIDS = MAINNET_PROGRAM_ID;
+ export const PROGRAMIDS = DEVNET_PROGRAM_ID;
```
Also
```diff
- marketProgramId: MAINNET_PROGRAM_ID.OPENBOOK_MARKET,
+ marketProgramId: PROGRAMIDS.OPENBOOK_MARKET,
```
2. Change `baseToken` and `quoteToken` as needed
3. Run the script, and get the error below,
```
/home/user/raydium-sdk-V1-demo/node_modules/@solana/web3.js/src/connection.ts:5921
      throw new SendTransactionError(
            ^
SendTransactionError: failed to send transaction: invalid transaction: Transaction loads an address table account that doesn't exist
    at Connection.sendEncodedTransaction (/home/user/raydium-sdk-V1-demo/node_modules/@solana/web3.js/src/connection.ts:5921:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.sendRawTransaction (/home/user/raydium-sdk-V1-demo/node_modules/@solana/web3.js/src/connection.ts:5880:20)
    at async Connection.sendTransaction (/home/user/raydium-sdk-V1-demo/node_modules/@solana/web3.js/src/connection.ts:5829:14) {
  logs: undefined
```

Have try the option `{ skipPreflight: true }` said in #7. no luck.

**Comment by jakerumbles** [comment]
In the `config.ts` file I changed to undefined. Had to do some digging to find that solution, like everything in this sdk lol.
![image](https://github.com/raydium-io/raydium-sdk-V1-demo/assets/25042987/e5195338-8810-46ca-8c74-06ffe979bbb0)

**Comment by Legend0619** [comment]
so creating pool on devnet was successful?
