### ISSUE TITLE
The error occurs when invoking ammCreatePool.ts

### ISSUE THREAD

**Issue by 100btcer** [raydium-io/raydium-sdk-V1-demo#17]
SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 2: custom program error: 0x1000078
    at Connection.sendEncodedTransaction (/Users/aurora/project/raydium-sdk-V1-demo/node_modules/@solana/web3.js/src/connection.ts:5921:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.sendRawTransaction (/Users/aurora/project/raydium-sdk-V1-demo/node_modules/@solana/web3.js/src/connection.ts:5880:20)
    at async Connection.sendTransaction (/Users/aurora/project/raydium-sdk-V1-demo/node_modules/@solana/web3.js/src/connection.ts:5829:14) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
    'Program log: Instruction: InitializeAccount',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3443 of 799850 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program HWy1jotHpo6UqeQxx49dpYYdQB8wj9Qk9MdxwjLvDHB8 invoke [1]',
    'Program log: initialize2: InitializeInstruction2 { nonce: 252, open_time: 1713880941, init_pc_amount: 0, init_coin_amount: 0 }',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
    'Program log: Instruction: SyncNative',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3045 of 779233 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
    'Program log: Instruction: InitializeMint',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2920 of 744020 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
    'Program log: Instruction: InitializeAccount',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4501 of 726518 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
    'Program log: Instruction: InitializeAccount',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3445 of 710416 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program EoTcMgcDRTJVZDMZWBoU6rhYHZfkNTVEAfz3uUJRcYGj invoke [2]',
    'Program EoTcMgcDRTJVZDMZWBoU6rhYHZfkNTVEAfz3uUJRcYGj consumed 1357 of 684916 compute units',
    'Program EoTcMgcDRTJVZDMZWBoU6rhYHZfkNTVEAfz3uUJRcYGj failed: custom program error: 0x1000078',
    'Program HWy1jotHpo6UqeQxx49dpYYdQB8wj9Qk9MdxwjLvDHB8 consumed 112848 of 796407 compute units',
    'Program HWy1jotHpo6UqeQxx49dpYYdQB8wj9Qk9MdxwjLvDHB8 failed: custom program error: 0x1000078'
  ]
}

**Comment by rudy5348** [comment]
The error occurred inside the market program, and you may need to provide tx base64 so that we can check for the problem.

**Comment by AJackTi** [comment]
I have the same issue. Did you fix it before? 

`'Program srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX invoke [2]',
    'Program srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX consumed 1357 of 701299 compute units',
    'Program srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX failed: custom program error: 0x1000078',
    'Program 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8 consumed 96465 of 796407 compute units',
    'Program 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8 failed: custom program error: 0x1000078'`

**Comment by AJackTi** [comment]
> The error occurred inside the market program, and you may need to provide tx base64 so that we can check for the problem.

Please help me check my problem. My tx base64 (I put log from `sendTx` function, and print log like that: `Buffer.from(iTx.serialize()).toString("base64")`): 
`AVQ7Kx5A78c+rHKrVmfhfu7c7PfX7fL7sXtckLXJKVB6nuKTenDKAQyA2U53PM3zfrN1EBpWdJP+07RXtGASKQeAAQAIE5SO5O9CS5HbWsYvWWmUQOAE6n4Rwdymqbe/SyjBGXvrAUQlZBa1TYHxas1XXGtlqvxoWeH46WTfAeo0l6anbJ9Kbi76rOyx3m0wVv4t2wGzh+1/K6TsX22sy4dTyriGprMYz/NDbu1IBWQWpEsoa8TcO6yM8KnIcgHmiM0hEXYlrKMgHKbfUPzudEa7MOrfymSiJ4+WLaBUcs49Fb1SQTzOEY1SdfrDJYTJt0t0HAKeiiJS4jYsrqCTXpzjsSGJ7tFw1xMJhY7uFiw5P827Epio+Gq93OjJFzAHYocYBRfTOp6oBpZhyKrxS22/zoBuB6QnEIwPHgq1zfRKnFjIqvFhUcscPp0g/YRKOoHODeiXX/AHv7/KUbB30tLvBJnYDnr1FCPcrVfJBd80btUjCJGKaPJ+HFyb8Pe1FS2iLHcvDo06bYxrTJLRfNk6fh8blkdVmuBHRh0JH6fnsaopkUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpBpuIV/6rgYT7aH9jRhjANdrEOdwa6ztVmKDwAAAAAAFL2UnENgLDPyB3kO0Wo1JMobmXXPEhoqkM/+x9+LaKzUFXsFgPMcX85EpiWC28+deO51lDoISjk7NQNo0iiZMIkRQkF+izN5p59kyUb1A2S7oNaWr+9zfnSHETyVspkCd5/f3z/y6DYV6qShd68DAYic45gTgcm5TTuPJ8CAeYLNWLEJHozyxIN1iS6kft6XVtgBFOawuB3N9f/qfnR7s/kkRDnQ+vHTai4Tsu4FJ9f101aPyyQuReQ/XyfbdMecQECwIAAXwDAAAAlI7k70JLkdtaxi9ZaZRA4ATqfhHB3Kapt79LKMEZe+sgAAAAAAAAAEJhTFRTQVpudW5yWHVEeUY5RXRDeGk0VXo2VGViaGg58B0fAAAAAAClAAAAAAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpDAQBDQATAQEOFQwUCxMCDwMEEA0FBgcRCBUSAAkBChoB/il4MGYAAAAAAAAAAAAAAAAQJwAAAAAAAAwDAQAAAQkBGY8fTDpFImPUE7LNF+vLwaDliHNk5iYaEqgXkuoWWj4AAwUHCw==`

**Comment by rudy5348** [comment]
> > The error occurred inside the market program, and you may need to provide tx base64 so that we can check for the problem.
> 
> Please help me check my problem. My tx base64 (I put log on `sendTx` function, and print log like that: `Buffer.from(iTx.serialize()).toString("base64")`): `AVQ7Kx5A78c+rHKrVmfhfu7c7PfX7fL7sXtckLXJKVB6nuKTenDKAQyA2U53PM3zfrN1EBpWdJP+07RXtGASKQeAAQAIE5SO5O9CS5HbWsYvWWmUQOAE6n4Rwdymqbe/SyjBGXvrAUQlZBa1TYHxas1XXGtlqvxoWeH46WTfAeo0l6anbJ9Kbi76rOyx3m0wVv4t2wGzh+1/K6TsX22sy4dTyriGprMYz/NDbu1IBWQWpEsoa8TcO6yM8KnIcgHmiM0hEXYlrKMgHKbfUPzudEa7MOrfymSiJ4+WLaBUcs49Fb1SQTzOEY1SdfrDJYTJt0t0HAKeiiJS4jYsrqCTXpzjsSGJ7tFw1xMJhY7uFiw5P827Epio+Gq93OjJFzAHYocYBRfTOp6oBpZhyKrxS22/zoBuB6QnEIwPHgq1zfRKnFjIqvFhUcscPp0g/YRKOoHODeiXX/AHv7/KUbB30tLvBJnYDnr1FCPcrVfJBd80btUjCJGKaPJ+HFyb8Pe1FS2iLHcvDo06bYxrTJLRfNk6fh8blkdVmuBHRh0JH6fnsaopkUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpBpuIV/6rgYT7aH9jRhjANdrEOdwa6ztVmKDwAAAAAAFL2UnENgLDPyB3kO0Wo1JMobmXXPEhoqkM/+x9+LaKzUFXsFgPMcX85EpiWC28+deO51lDoISjk7NQNo0iiZMIkRQkF+izN5p59kyUb1A2S7oNaWr+9zfnSHETyVspkCd5/f3z/y6DYV6qShd68DAYic45gTgcm5TTuPJ8CAeYLNWLEJHozyxIN1iS6kft6XVtgBFOawuB3N9f/qfnR7s/kkRDnQ+vHTai4Tsu4FJ9f101aPyyQuReQ/XyfbdMecQECwIAAXwDAAAAlI7k70JLkdtaxi9ZaZRA4ATqfhHB3Kapt79LKMEZe+sgAAAAAAAAAEJhTFRTQVpudW5yWHVEeUY5RXRDeGk0VXo2VGViaGg58B0fAAAAAAClAAAAAAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpDAQBDQATAQEOFQwUCxMCDwMEEA0FBgcRCBUSAAkBChoB/il4MGYAAAAAAAAAAAAAAAAQJwAAAAAAAAwDAQAAAQkBGY8fTDpFImPUE7LNF+vLwaDliHNk5iYaEqgXkuoWWj4AAwUHCw==`

This is because openbook failed to check the queue length.

**Comment by MD-RanaHardik** [comment]
> > > The error occurred inside the market program, and you may need to provide tx base64 so that we can check for the problem.
> > 
> > 
> > Please help me check my problem. My tx base64 (I put log on `sendTx` function, and print log like that: `Buffer.from(iTx.serialize()).toString("base64")`): `AVQ7Kx5A78c+rHKrVmfhfu7c7PfX7fL7sXtckLXJKVB6nuKTenDKAQyA2U53PM3zfrN1EBpWdJP+07RXtGASKQeAAQAIE5SO5O9CS5HbWsYvWWmUQOAE6n4Rwdymqbe/SyjBGXvrAUQlZBa1TYHxas1XXGtlqvxoWeH46WTfAeo0l6anbJ9Kbi76rOyx3m0wVv4t2wGzh+1/K6TsX22sy4dTyriGprMYz/NDbu1IBWQWpEsoa8TcO6yM8KnIcgHmiM0hEXYlrKMgHKbfUPzudEa7MOrfymSiJ4+WLaBUcs49Fb1SQTzOEY1SdfrDJYTJt0t0HAKeiiJS4jYsrqCTXpzjsSGJ7tFw1xMJhY7uFiw5P827Epio+Gq93OjJFzAHYocYBRfTOp6oBpZhyKrxS22/zoBuB6QnEIwPHgq1zfRKnFjIqvFhUcscPp0g/YRKOoHODeiXX/AHv7/KUbB30tLvBJnYDnr1FCPcrVfJBd80btUjCJGKaPJ+HFyb8Pe1FS2iLHcvDo06bYxrTJLRfNk6fh8blkdVmuBHRh0JH6fnsaopkUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpBpuIV/6rgYT7aH9jRhjANdrEOdwa6ztVmKDwAAAAAAFL2UnENgLDPyB3kO0Wo1JMobmXXPEhoqkM/+x9+LaKzUFXsFgPMcX85EpiWC28+deO51lDoISjk7NQNo0iiZMIkRQkF+izN5p59kyUb1A2S7oNaWr+9zfnSHETyVspkCd5/f3z/y6DYV6qShd68DAYic45gTgcm5TTuPJ8CAeYLNWLEJHozyxIN1iS6kft6XVtgBFOawuB3N9f/qfnR7s/kkRDnQ+vHTai4Tsu4FJ9f101aPyyQuReQ/XyfbdMecQECwIAAXwDAAAAlI7k70JLkdtaxi9ZaZRA4ATqfhHB3Kapt79LKMEZe+sgAAAAAAAAAEJhTFRTQVpudW5yWHVEeUY5RXRDeGk0VXo2VGViaGg58B0fAAAAAAClAAAAAAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpDAQBDQATAQEOFQwUCxMCDwMEEA0FBgcRCBUSAAkBChoB/il4MGYAAAAAAAAAAAAAAAAQJwAAAAAAAAwDAQAAAQkBGY8fTDpFImPUE7LNF+vLwaDliHNk5iYaEqgXkuoWWj4AAwUHCw==`
> 
> This is because openbook failed to check the queue length.

how to solve this issue?
